// Blob storage URLs for media assets
// Auto-generated by migration script - DO NOT EDIT MANUALLY
// Last updated: 2025-11-14T04:10:54.156Z

export const blobUrls = {
  "scenes": {
    "autumn-lake-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/autumn-lake-thumbnail.jpeg",
    "autumn-lake.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/autumn-lake.mp4",
    "beach.jpg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/beach.jpg",
    "black-hole-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/black-hole-thumbnail.jpeg",
    "black-hole.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/black-hole.mp4",
    "charming-cafe-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/charming-cafe-thumbnail.jpeg",
    "charming-cafe.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/charming-cafe.mp4",
    "cherry-blossom-lake-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/cherry-blossom-lake-thumbnail.jpeg",
    "cherry-blossom-lake.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/cherry-blossom-lake.mp4",
    "cozy-cafe.jpg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/cozy-cafe.jpg",
    "dark-star-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/dark-star-thumbnail.jpeg",
    "dark-star.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/dark-star.mp4",
    "magical-forest-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/magical-forest-thumbnail.jpeg",
    "magical-forest.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/magical-forest.mp4",
    "snow-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/snow-thumbnail.jpeg",
    "snow.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/snow.mp4",
    "starry-night-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/starry-night-thumbnail.jpeg",
    "starry-night.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/starry-night.mp4",
    "summer-village-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/summer-village-thumbnail.jpeg",
    "summer-village.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/summer-village.mp4",
    "sunbeam-forest-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/sunbeam-forest-thumbnail.jpeg",
    "sunbeam-forest.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/sunbeam-forest.mp4",
    "sunset-beach-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/sunset-beach-thumbnail.jpeg",
    "sunset-beach.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/sunset-beach.mp4",
    "winter-city-thumbnail.jpeg": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/winter-city-thumbnail.jpeg",
    "winter-city.mp4": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/scenes/winter-city.mp4"
  },
  "sounds": {
    "burning-fire.mp3": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/sounds/burning-fire.mp3",
    "heavy-rain.mp3": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/sounds/heavy-rain.mp3",
    "light-rain.mp3": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/sounds/light-rain.mp3",
    "ocean-waves.mp3": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/sounds/ocean-waves.mp3"
  },
  "assets": {
    "timer-complete.mp3": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/timer-complete.mp3",
    "chill-with-taiki.png": "https://p6muu9eu7tfnjh3y.public.blob.vercel-storage.com/chill-with-taiki.png"
  }
};

// Helper function to get blob URL or fallback to local
export function getBlobUrl(category: keyof typeof blobUrls, filename: string): string {
  const url = blobUrls[category]?.[filename as keyof typeof blobUrls[typeof category]] as string | undefined;
  
  // If blob URL exists and is not empty, use it; otherwise fallback to local
  if (url && url.length > 0) {
    return url;
  }
  
  // Fallback to local public files
  if (category === 'scenes') {
    return `/scenes/${filename}`;
  } else if (category === 'sounds') {
    return `/sounds/${filename}`;
  } else {
    return `/${filename}`;
  }
}
